"use client";

import { motion, useReducedMotion } from "motion/react";
import { Reveal } from "@/components/reveal";

const nodes = ["Lead", "AI qualification", "CRM", "Follow-up", "Sales", "Reporting"];
export function AutomationSystem() {
  const reduceMotion = useReducedMotion();
  return <section id="systems" className="py-24 sm:py-32"><div className="container"><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="eyebrow">Systems thinking</p><h2 className="section-heading mt-4">Connected automations create compounding value.</h2><p className="mt-6 max-w-md leading-7 text-white/57">The real leverage comes from the hand-offs. We design every step to pass useful context forward, so no lead, task or insight disappears between tools.</p></Reveal><Reveal delay={.12}><div className="relative overflow-hidden border border-white/10 bg-[#0a0d15] p-5 sm:p-8"><div className="grid-bg absolute inset-0 opacity-50" /><div className="relative"><div className="mb-7 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.14em] text-white/45">ReplyFlow system map</span><span className="flex items-center gap-2 text-xs text-cyan-200"><span className="size-1.5 rounded-full bg-cyan-300 shadow-[0_0_10px_#67e8f9]" /> Live flow</span></div><div className="relative grid gap-3 sm:grid-cols-2">{nodes.map((node, index) => <div key={node} className="relative"><motion.div initial={reduceMotion ? false : { opacity: 0, scale: .96 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: .25 + index * .08, duration: .35 }} className="relative z-10 flex min-h-20 items-center gap-3 border border-white/12 bg-[#101521] px-4 text-sm font-medium shadow-[0_10px_30px_rgba(0,0,0,.18)]"><span className="grid size-7 place-items-center rounded-full border border-cyan-200/25 bg-cyan-200/10 text-[10px] text-cyan-100">{String(index + 1).padStart(2, "0")}</span>{node}</motion.div>{index < nodes.length - 1 && <motion.span aria-hidden="true" className="absolute -bottom-3 left-1/2 z-0 hidden h-3 w-px bg-gradient-to-b from-cyan-300/70 to-violet-400/20 sm:block" animate={reduceMotion ? undefined : { opacity: [.35, 1, .35] }} transition={{ duration: 1.7, repeat: Infinity, delay: index * .14 }} />}</div>)}</div><p className="mt-7 text-xs leading-5 text-white/40">Every connection is designed to preserve context, trigger the next action and create a clear record.</p></div></div></Reveal></div></div></section>;
}
